server:
  port: ${SERVER_PORT}

spring:
  r2dbc:
    url: r2dbc:pool:postgres://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    locations: classpath:db/migration
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  password:
    encoder:
      secret: ${JWT_SECRET}
      iteration: ${JWT_ITERATION}
      keylength: ${JWT_KEY_LENGTH}
  secret: ${JWT_TOKEN_SECRET}
  expiration: ${JWT_TOKEN_EXPIRATION}
  issuer: ${JWT_TOKEN_ISSUER}
